### ISSUE TITLE
the end *  of the path  dont matchs some cases

### ISSUE THREAD

**Issue by tylitianrui** [api7/lua-resty-radixtree#106]
according [doc](https://github.com/api7/lua-resty-radixtree#new) ，  if the end of the path is *, it means that this is a prefix path.  most cases  do it well，but  path ， like /*/ping* , dont.   it matches  _/xxx/ping_     ,   _/xxx/ping_ ,  _/xxx/pinggggg_  ,   _/xxx/xxx/ping_   and  so  on.  but  it dont  match  some cases, like    _/xxx/pingxxx_ (x is  not g) ,   /xxx/ping/xxx

**Comment by membphis** [comment]
Can you provide a specific test case?

you can take a look at:

https://github.com/api7/lua-resty-radixtree/blob/master/benchmark/match-prefix.lua

**Comment by membphis** [comment]
ping @tylitianrui
