### ISSUE TITLE
'Unauthenticated git protocol on port 9418 is no longer supported' while installing via luarocks

### ISSUE THREAD

**Issue by mong0520** [api7/lua-resty-radixtree#107]
I use `RUN luarocks install lua-resty-radixtree 2.8.1-0` in the Dockerfile to install lua-resty-radixtree, but today the build process reports following error message and build failed.

Same issue here for the reference:
https://github.com/leafo/gifine/issues/27

```
 > [27/28] RUN luarocks install lua-resty-radixtree 2.8.1-0:
#31 1.023 Installing https://luarocks.org/lua-resty-radixtree-2.8.1-0.src.rock
#31 1.654 Missing dependencies for lua-resty-radixtree 2.8.1-0:
#31 1.654    lua-resty-expr 1.3.0 (not installed)
#31 1.654
#31 1.654 lua-resty-radixtree 2.8.1-0 depends on lua-resty-ipmatcher (0.6-0 installed)
#31 1.654 lua-resty-radixtree 2.8.1-0 depends on lua-resty-expr 1.3.0 (not installed)
#31 1.654 Installing https://luarocks.org/lua-resty-expr-1.3.0-0.rockspec
#31 1.665 Cloning into 'lua-resty-expr'...
#31 2.254 fatal: remote error:
#31 2.254   The unauthenticated git protocol on port 9418 is no longer supported.
#31 2.254 Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
#31 2.259
#31 2.259 Error: Failed installing dependency: https://luarocks.org/lua-resty-expr-1.3.0-0.rockspec - Failed cloning git repository.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c luarocks install lua-resty-radixtree 2.8.1-0]: exit code: 1
make: *** [local_build] Error 17

```

**Comment by jy5275** [comment]
Seems that you should use LuaRocks 3.8.0 instead
As described in https://github.com/luarocks/luarocks/blob/master/CHANGELOG.md
> The raw git:// protocol will stop working on GitHub. LuaRocks already supports git+https:// as an alternative, but to avoid having to update every rockspec in the repository that uses git://github.com, which would require a large coordinated effort, LuaRocks now auto-converts github.com and www.github.com URLs that use git:// to git+https://

**Comment by membphis** [comment]
same to: https://github.com/api7/jsonschema/issues/68
