### ISSUE TITLE
allow user-define filter function in route, it has security issues.

### ISSUE THREAD

**Issue by membphis** [api7/lua-resty-radixtree#17]

**Comment by moonming** [comment]
what's the security issues? Can you show one example?

**Comment by membphis** [comment]
Because it's an embedded Lua script, in theory, you can do anything, such as breaking the current ngx.ctx structure.

```lua
filter_fun = function
ngx.ctx = nil
end
```

**Comment by moonming** [comment]
user can also write the bad code in plugin, not only the  user-define filter function in route.
If this issue can cause from client request, I think it's a security problem, and I don't think bad code is security issue.

**Comment by membphis** [comment]
we can close this issue now.
