### ISSUE TITLE
How does the request path support regular matching?

### ISSUE THREAD

**Issue by wangxiaochuang** [api7/lua-resty-radixtree#34]

**Comment by moonming** [comment]
you can implement in the `filter_fun`.

**Comment by moonming** [comment]
and welcome add this to the doc.

**Comment by membphis** [comment]
@wangxiaochuang here is a another way

```lua
local rx = radix.new({
    {
        paths = "/aa/*",
        metadata = "metadata /aa",
        vars = {
            {"arg_uri", "~~", [[/aa/\d+]]},
        },
    }
})
```

**Comment by wood-zhang** [comment]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/62324191/212015591-47b549c1-a45f-41bc-821d-62575563b5e7.png">

{
  "uri": "/*",
  "name": "woodtest",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "host": "woodtest.com",
  "vars": [
    [
      "request_uri",
      "~*",
      "^.+\\.txt$"
    ]
  ],
  "plugins": {
    "proxy-rewrite": {
      "host": "xxx.com"
    }
  },
  "upstream_id": "1231423423342423534",
  "labels": {
    "API_VERSION": "V1"
  },
  "enable_websocket": true,
  "status": 1
}
