### ISSUE TITLE
bug: record which matches the current request error

### ISSUE THREAD

**Issue by tzssangglass** [api7/lua-resty-radixtree#67]
With the following two conditions met:

- opts.method matched routr.methods
- opts.matched = {}

the route match will fail.

case references: apache/apisix#1574

bug causes
https://github.com/api7/lua-resty-radixtree/blob/6b5d65eb9853c91b1d23cc4cea8941be74bb5f20/lib/resty/radixtree.lua#L663-L666
between `match_route_opts` and `compare_param` , should check whether it is resuful style url pass parameter, or prefix matching, the prefix matching does not need to be entered `compare_param`.

**Comment by tzssangglass** [comment]
I will fix it

**Comment by membphis** [comment]
Can you provide a minimal test case first?

**Comment by tzssangglass** [comment]
> Can you provide a minimal test case first?


```
# vim:set ft= ts=4 sw=4 et fdm=marker:

use t::RX 'no_plan';

repeat_each(1);
run_tests();

__DATA__

=== TEST 1: prefix matching with method, and matched is not nil.
--- config
    location /t {
        content_by_lua_block {
            local radix = require("resty.radixtree")
            local rx = radix.new({
                {
                    paths = "/hello*",
                    methods = {"GET"},
                    metadata = "metadata prefix matching with GET, matched = {}",
                },
            })

            local opts = {method = "GET", matched = {}}
            ngx.say(rx:match("/hello1", opts))

        }
    }
--- request
GET /t
--- no_error_log
[error]
--- response_body
metadata prefix matching with GET, matched = {}
```
