### ISSUE TITLE
lua-resty-radixtree in docker env

### ISSUE THREAD

**Issue by ciyoe** [api7/lua-resty-radixtree#80]
dev-env: OSX
run-env: docker (which image is `openresty/openresty:lastest`)

when i installed `lua-resty-radixtree` in OSX, it would make `librestyradixtree.dylib`, 
but the `openresty/openresty:lastest` image is based on `debian` OS, it should required `librestyradixtree.so` which was not make in install step

the error follow below 

```
openresty    | tried above paths but can not load librestyradixtree.so

```
 
any idea fix this typo in friendly. just not like exec install command in docker containers.

**Comment by membphis** [comment]
you can take a look at this link:

https://github.com/openresty/lua-resty-balancer/blob/master/Makefile#L21-L24

need to update the Makefile. good luck

**Comment by membphis** [comment]
any news? @ciyoe
