### ISSUE TITLE
build in mingw64 environment

### ISSUE THREAD

**Issue by moorefu** [api7/lua-resty-radixtree#81]
当我在mingw环境下编译lua-resty-radixtree时，我发现只要去掉easy_rax.c文件中的以下引用就可以编译通过。
```
...
#include <netinet/in.h>
#include <arpa/inet.h>
...
```
那请问引入这两个库的用途是什么呢，除了在 [lua-resty-ipmatcher](https://github.com/api7/lua-resty-ipmatcher/blob/master/resty/ipmatcher.lua#L35) 这里发现有利用ffi动态加载了这两个库的方法，还有其他地方有用到么？

**Comment by membphis** [comment]
it was used to check if the input IP address is a valid value

**Comment by moorefu** [comment]
> it was used to check if the input IP address is a valid value

so can I use ws2_32.dll  to do this thing?

**Comment by membphis** [comment]
sorry I do not know this, I mainly use Linux now. 
welcome to make a try
