### ISSUE TITLE
We should not use ':' as the param indicator

### ISSUE THREAD

**Issue by spacewander** [api7/lua-resty-radixtree#82]
Now we use ':' to indicate a param name like this: https://github.com/api7/lua-resty-radixtree#parameters-in-path
However, ":" is legal in uri and is recommended to indicate a custom HTTP method in RESTful API, for example, in Google's https://cloud.google.com/apis/design/custom_methods.

**Comment by tokers** [comment]
How other route frameworks handle this problem? Like go-gin and ruby on rails.

**Comment by membphis** [comment]
We can add a new option that allows users to choose the working mechanism.

**Comment by membphis** [comment]
we have supported `no_param_match`

![image](https://user-images.githubusercontent.com/6814606/125879371-f6aa8227-7f96-4a48-ac88-c41dfee64519.png)
