### ISSUE TITLE
request help: install: 无法获取"librestyradixtree.so" 的文件状态(stat): 没有那个文件或目录

### ISSUE THREAD

**Issue by qwxingzhe** [api7/lua-resty-radixtree#87]
当我更新apisix-dashboard的schema.json时遇到了下面的问题，lua: ./apisix/admin/init.lua:19: module 'resty.radixtree' not found：

When I update theapisix-dashboard schema.json I met the following problems when I was working,lua: ./apisix/admin/init.lua:19: module 'resty.radixtree' not found:

![image](https://user-images.githubusercontent.com/7071651/103449982-cff61000-4cea-11eb-88fc-e30ab362a7e4.png)

于是我安装lua-resty-radixtree，但又遇到了下面的问题：

So I installed lua-resty-radixtree, but I encountered the following problem:

![image](https://user-images.githubusercontent.com/7071651/103449942-3cbcda80-4cea-11eb-9676-2857662d6e58.png)
![image](https://user-images.githubusercontent.com/7071651/103449945-46464280-4cea-11eb-85e4-897d73e7687c.png)
![image](https://user-images.githubusercontent.com/7071651/103449954-6bd34c00-4cea-11eb-8458-8a8242100cbd.png)

**Comment by membphis** [comment]
you should create a new issue at https://github.com/apache/apisix-dashboard

it should be a bug of  https://github.com/apache/apisix-dashboard.
