### ISSUE TITLE
release new version 

### ISSUE THREAD

**Issue by membphis** [api7/lua-resty-radixtree#90]
the `lua-resty-expr` had released version `v1.1.0`, I think we need to release a new version of lua-resty-radixtree.

@Firstsawyou what do you think?

**Comment by Firstsawyou** [comment]
> the `lua-resty-expr` had released version `v1.1.0`, I think we need to release a new version of lua-resty-radixtree.
> 
> @Firstsawyou what do you think?

Yes, it is necessary, let me try it.
