### ISSUE TITLE
radixtree free memory fail, nginx worker exit

### ISSUE THREAD

**Issue by jfboys** [api7/lua-resty-radixtree#92]
nginx worker exit while run radixtree test
The error message is as follows
2021/01/26 04:15:41 [alert] 10469#10469: worker process 10470 exited on signal 11

nginx.conf example :

server {
    listen 127.0.0.1:80;

      location /test {
            content_by_lua_block {
                    local radix = require("resty.radixtree")
                    local route_count = 1000 * 100
                    local match_times = 1000 * 1000 * 10
                    
                    local routes = {}
                    for i = 1, route_count do
                        routes[i] = {paths = {"/user" .. i .. "/:name"}, metadata = i}
                    end
                    
                    local rx = radix.new(routes)
                    ngx.update_time()
                    local start_time = ngx.now()
                    
                    local res
                    local path = "/user500/gordon"
                    for _ = 1, match_times do
                        res = rx:match(path)
                    end
                    
                    ngx.update_time()
                    local used_time = ngx.now() - start_time
                    ngx.say("matched res: ", res)
                    ngx.say("route count: ", route_count)
                    ngx.say("match times: ", match_times)
                    ngx.say("time used  : ", used_time, " sec")
                    ngx.say("QPS        : ", math.floor(match_times / used_time))
                    ngx.say("each time  : ", used_time * 1000 * 1000 / match_times, " ns")
            }
     }
}

Recurrence request ：
curl http://127.0.0.1:80/test -v

more err message : 
10489#10489: *4 lua entry thread aborted: runtime error: /usr/local/nginx/lua/resty/radixtree.lua:418: missing declaration for symbol 'free'

fix commit ： https://github.com/api7/lua-resty-radixtree/compare/master...jfboys:fix-free-fail

**Comment by membphis** [comment]
it works fine at my side. I think you need to provide more information ^_^

I tested with commit https://github.com/api7/lua-resty-radixtree/commit/6207ca54ebeadf4fccd67adb535eb11027b223e7

```shell
$ resty -I=./lib -I=./deps/share/lua/5.1 test.lua
matched res: 500
route count: 100000
match times: 10000000
time used  : 3.8529999256134 sec
QPS        : 2595380
each time  : 0.38529999256134 ns

$ cat test.lua
local radix = require("resty.radixtree")
                local route_count = 1000 * 100
                local match_times = 1000 * 1000 * 10

                local routes = {}
                for i = 1, route_count do
                    routes[i] = {paths = {"/user" .. i .. "/:name"}, metadata = i}
                end

                local rx = radix.new(routes)
                ngx.update_time()
                local start_time = ngx.now()

                local res
                local path = "/user500/gordon"
                for _ = 1, match_times do
                    res = rx:match(path)
                end

                ngx.update_time()
                local used_time = ngx.now() - start_time
                ngx.say("matched res: ", res)
                ngx.say("route count: ", route_count)
                ngx.say("match times: ", match_times)
                ngx.say("time used  : ", used_time, " sec")
                ngx.say("QPS        : ", math.floor(match_times / used_time))
                ngx.say("each time  : ", used_time * 1000 * 1000 / match_times, " ns")

**Comment by jfboys** [comment]
lua script running on the nginx worker process

review radixtree code  on the free function

**Comment by membphis** [comment]
you can add this code and make it a try, if it works, welcome or ^_^
```lua
void free(void *ptr);
```

**Comment by jfboys** [comment]
In the first comment, I have submitted this fix, which is consistent with your code

**Comment by membphis** [comment]
it works fine at my side. 

if you still have an issue, please email me. my email: membphis@gmail.com
we may need to access your machine.

```lua
$ cat test.lua
local radix = require("resty.radixtree")
                local route_count = 1000 * 100
                local match_times = 1000 * 1000 * 10

                local routes = {}
                for i = 1, route_count do
                    routes[i] = {paths = {"/user" .. i .. "/:name"}, metadata = i}
                end

                local rx = radix.new(routes)
                ngx.update_time()
                local start_time = ngx.now()

                local res
                local path = "/user500/gordon"
                for _ = 1, match_times do
                    res = rx:match(path)
                end

                ngx.update_time()
                local used_time = ngx.now() - start_time
                ngx.say("matched res: ", res)
                ngx.say("route count: ", route_count)
                ngx.say("match times: ", match_times)
                ngx.say("time used  : ", used_time, " sec")
                ngx.say("QPS        : ", math.floor(match_times / used_time))
                ngx.say("each time  : ", used_time * 1000 * 1000 / match_times, " ns")

$ git diff > mm.log && cat mm.log
diff --git a/lib/resty/radixtree.lua b/lib/resty/radixtree.lua
index df0262e..3be556b 100644
--- a/lib/resty/radixtree.lua
+++ b/lib/resty/radixtree.lua
@@ -117,6 +117,8 @@ ffi_cdef[[
     int radix_tree_stop(void *it);

     void *radix_tree_new_it(void *t);
+
+    void free(void *ptr);
 ]]
```

**Comment by jfboys** [comment]
It works fine after repair
